language: php

php:
    - 5.5
    - 5.6
    - hhvm
    
notifications:
  slack: idevbe:xL5Pzkoj7FVQTybIUjUHEYCq

before_script:
    - travis_retry composer self-update
    - travis_retry composer install --no-interaction --prefer-source --dev
    - pip install --user codecov
