language: php

services:
 - mysql

matrix:
  php:
    - 5.6
    - 5.5
    - 7.0

  allow_failures:
    - php: hhvm
    
notifications:
  slack: idevbe:xL5Pzkoj7FVQTybIUjUHEYCq

before_script:
    - travis_retry composer self-update
    - travis_retry composer install --no-interaction --prefer-source --dev
    - php artisan migrate --database=sqlite --force
    - pip install --user codecov
